sudo: false

language: node_js

node_js:
  - "lts/*"

branches:
  only:
    - master

before_install:
  - curl -fsSL https://get.pnpm.io/install.sh | sh -

install:
  - pnpm install

cache:
  yarn: true
  directories:
    - ".eslintcache"
    - "node_modules"

script:
  - pnpm run test
  - pnpm run coveralls
